version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
      - PGDATA="/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - habrdb-data:/var/lib/postgresql/data
    command: postgres
    restart: always

volumes:
  habrdb-data: